/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAdditiveExpAdditiveExp extends PAdditiveExp
{
    private PAdditiveExp _additiveExp_;
    private TPlus _plus_;
    private PDividitiveExp _dividitiveExp_;

    public AAdditiveExpAdditiveExp()
    {
        // Constructor
    }

    public AAdditiveExpAdditiveExp(
        @SuppressWarnings("hiding") PAdditiveExp _additiveExp_,
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PDividitiveExp _dividitiveExp_)
    {
        // Constructor
        setAdditiveExp(_additiveExp_);

        setPlus(_plus_);

        setDividitiveExp(_dividitiveExp_);

    }

    @Override
    public Object clone()
    {
        return new AAdditiveExpAdditiveExp(
            cloneNode(this._additiveExp_),
            cloneNode(this._plus_),
            cloneNode(this._dividitiveExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditiveExpAdditiveExp(this);
    }

    public PAdditiveExp getAdditiveExp()
    {
        return this._additiveExp_;
    }

    public void setAdditiveExp(PAdditiveExp node)
    {
        if(this._additiveExp_ != null)
        {
            this._additiveExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._additiveExp_ = node;
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PDividitiveExp getDividitiveExp()
    {
        return this._dividitiveExp_;
    }

    public void setDividitiveExp(PDividitiveExp node)
    {
        if(this._dividitiveExp_ != null)
        {
            this._dividitiveExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dividitiveExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._additiveExp_)
            + toString(this._plus_)
            + toString(this._dividitiveExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._additiveExp_ == child)
        {
            this._additiveExp_ = null;
            return;
        }

        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._dividitiveExp_ == child)
        {
            this._dividitiveExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._additiveExp_ == oldChild)
        {
            setAdditiveExp((PAdditiveExp) newChild);
            return;
        }

        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._dividitiveExp_ == oldChild)
        {
            setDividitiveExp((PDividitiveExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
