/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAdecfuncDecFunc extends PDecFunc
{
    private PTipoFunc _tipoFunc_;
    private TId _id_;
    private final LinkedList<PParametro> _parametro_ = new LinkedList<PParametro>();
    private PExp _exp_;

    public AAdecfuncDecFunc()
    {
        // Constructor
    }

    public AAdecfuncDecFunc(
        @SuppressWarnings("hiding") PTipoFunc _tipoFunc_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _parametro_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setTipoFunc(_tipoFunc_);

        setId(_id_);

        setParametro(_parametro_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAdecfuncDecFunc(
            cloneNode(this._tipoFunc_),
            cloneNode(this._id_),
            cloneList(this._parametro_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdecfuncDecFunc(this);
    }

    public PTipoFunc getTipoFunc()
    {
        return this._tipoFunc_;
    }

    public void setTipoFunc(PTipoFunc node)
    {
        if(this._tipoFunc_ != null)
        {
            this._tipoFunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoFunc_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PParametro> getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(List<?> list)
    {
        for(PParametro e : this._parametro_)
        {
            e.parent(null);
        }
        this._parametro_.clear();

        for(Object obj_e : list)
        {
            PParametro e = (PParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parametro_.add(e);
        }
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoFunc_)
            + toString(this._id_)
            + toString(this._parametro_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoFunc_ == child)
        {
            this._tipoFunc_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._parametro_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoFunc_ == oldChild)
        {
            setTipoFunc((PTipoFunc) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PParametro> i = this._parametro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
