/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAdicaoRelacao extends PRelacao
{
    private PAdicao _adicao_;

    public AAdicaoRelacao()
    {
        // Constructor
    }

    public AAdicaoRelacao(
        @SuppressWarnings("hiding") PAdicao _adicao_)
    {
        // Constructor
        setAdicao(_adicao_);

    }

    @Override
    public Object clone()
    {
        return new AAdicaoRelacao(
            cloneNode(this._adicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdicaoRelacao(this);
    }

    public PAdicao getAdicao()
    {
        return this._adicao_;
    }

    public void setAdicao(PAdicao node)
    {
        if(this._adicao_ != null)
        {
            this._adicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._adicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._adicao_ == child)
        {
            this._adicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._adicao_ == oldChild)
        {
            setAdicao((PAdicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
