/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAexplist2ExpList extends PExpList
{
    private PExp _exp_;
    private final LinkedList<PExpList> _expList_ = new LinkedList<PExpList>();

    public AAexplist2ExpList()
    {
        // Constructor
    }

    public AAexplist2ExpList(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") List<?> _expList_)
    {
        // Constructor
        setExp(_exp_);

        setExpList(_expList_);

    }

    @Override
    public Object clone()
    {
        return new AAexplist2ExpList(
            cloneNode(this._exp_),
            cloneList(this._expList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAexplist2ExpList(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public LinkedList<PExpList> getExpList()
    {
        return this._expList_;
    }

    public void setExpList(List<?> list)
    {
        for(PExpList e : this._expList_)
        {
            e.parent(null);
        }
        this._expList_.clear();

        for(Object obj_e : list)
        {
            PExpList e = (PExpList) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expList_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._expList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._expList_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        for(ListIterator<PExpList> i = this._expList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpList) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
