/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAprograma3Programa extends PPrograma
{
    private final LinkedList<PDecVar> _decVar_ = new LinkedList<PDecVar>();
    private final LinkedList<PDecProc> _decProc_ = new LinkedList<PDecProc>();

    public AAprograma3Programa()
    {
        // Constructor
    }

    public AAprograma3Programa(
        @SuppressWarnings("hiding") List<?> _decVar_,
        @SuppressWarnings("hiding") List<?> _decProc_)
    {
        // Constructor
        setDecVar(_decVar_);

        setDecProc(_decProc_);

    }

    @Override
    public Object clone()
    {
        return new AAprograma3Programa(
            cloneList(this._decVar_),
            cloneList(this._decProc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAprograma3Programa(this);
    }

    public LinkedList<PDecVar> getDecVar()
    {
        return this._decVar_;
    }

    public void setDecVar(List<?> list)
    {
        for(PDecVar e : this._decVar_)
        {
            e.parent(null);
        }
        this._decVar_.clear();

        for(Object obj_e : list)
        {
            PDecVar e = (PDecVar) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decVar_.add(e);
        }
    }

    public LinkedList<PDecProc> getDecProc()
    {
        return this._decProc_;
    }

    public void setDecProc(List<?> list)
    {
        for(PDecProc e : this._decProc_)
        {
            e.parent(null);
        }
        this._decProc_.clear();

        for(Object obj_e : list)
        {
            PDecProc e = (PDecProc) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decProc_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVar_)
            + toString(this._decProc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVar_.remove(child))
        {
            return;
        }

        if(this._decProc_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecVar> i = this._decVar_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecVar) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PDecProc> i = this._decProc_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecProc) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
