/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AArrArrAttr extends PArrAttr
{
    private PArrAttr _arrAttr_;
    private TLBrkt _lBrkt_;
    private PExp _exp_;
    private TRBrkt _rBrkt_;

    public AArrArrAttr()
    {
        // Constructor
    }

    public AArrArrAttr(
        @SuppressWarnings("hiding") PArrAttr _arrAttr_,
        @SuppressWarnings("hiding") TLBrkt _lBrkt_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TRBrkt _rBrkt_)
    {
        // Constructor
        setArrAttr(_arrAttr_);

        setLBrkt(_lBrkt_);

        setExp(_exp_);

        setRBrkt(_rBrkt_);

    }

    @Override
    public Object clone()
    {
        return new AArrArrAttr(
            cloneNode(this._arrAttr_),
            cloneNode(this._lBrkt_),
            cloneNode(this._exp_),
            cloneNode(this._rBrkt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrArrAttr(this);
    }

    public PArrAttr getArrAttr()
    {
        return this._arrAttr_;
    }

    public void setArrAttr(PArrAttr node)
    {
        if(this._arrAttr_ != null)
        {
            this._arrAttr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrAttr_ = node;
    }

    public TLBrkt getLBrkt()
    {
        return this._lBrkt_;
    }

    public void setLBrkt(TLBrkt node)
    {
        if(this._lBrkt_ != null)
        {
            this._lBrkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrkt_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TRBrkt getRBrkt()
    {
        return this._rBrkt_;
    }

    public void setRBrkt(TRBrkt node)
    {
        if(this._rBrkt_ != null)
        {
            this._rBrkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrAttr_)
            + toString(this._lBrkt_)
            + toString(this._exp_)
            + toString(this._rBrkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrAttr_ == child)
        {
            this._arrAttr_ = null;
            return;
        }

        if(this._lBrkt_ == child)
        {
            this._lBrkt_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._rBrkt_ == child)
        {
            this._rBrkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrAttr_ == oldChild)
        {
            setArrAttr((PArrAttr) newChild);
            return;
        }

        if(this._lBrkt_ == oldChild)
        {
            setLBrkt((TLBrkt) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._rBrkt_ == oldChild)
        {
            setRBrkt((TRBrkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
