/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AAttrComandoComando extends PComando
{
    private PArrAttr _arrAttr_;
    private PExp _exp_;

    public AAttrComandoComando()
    {
        // Constructor
    }

    public AAttrComandoComando(
        @SuppressWarnings("hiding") PArrAttr _arrAttr_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setArrAttr(_arrAttr_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AAttrComandoComando(
            cloneNode(this._arrAttr_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttrComandoComando(this);
    }

    public PArrAttr getArrAttr()
    {
        return this._arrAttr_;
    }

    public void setArrAttr(PArrAttr node)
    {
        if(this._arrAttr_ != null)
        {
            this._arrAttr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrAttr_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arrAttr_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arrAttr_ == child)
        {
            this._arrAttr_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arrAttr_ == oldChild)
        {
            setArrAttr((PArrAttr) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
