/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABaseTipoFunc extends PTipoFunc
{
    private PTipoKw _tipoKw_;

    public ABaseTipoFunc()
    {
        // Constructor
    }

    public ABaseTipoFunc(
        @SuppressWarnings("hiding") PTipoKw _tipoKw_)
    {
        // Constructor
        setTipoKw(_tipoKw_);

    }

    @Override
    public Object clone()
    {
        return new ABaseTipoFunc(
            cloneNode(this._tipoKw_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseTipoFunc(this);
    }

    public PTipoKw getTipoKw()
    {
        return this._tipoKw_;
    }

    public void setTipoKw(PTipoKw node)
    {
        if(this._tipoKw_ != null)
        {
            this._tipoKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoKw_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoKw_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoKw_ == child)
        {
            this._tipoKw_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoKw_ == oldChild)
        {
            setTipoKw((PTipoKw) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
