/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanExpExp extends PExp
{
    private PBooleanExp _booleanExp_;

    public ABooleanExpExp()
    {
        // Constructor
    }

    public ABooleanExpExp(
        @SuppressWarnings("hiding") PBooleanExp _booleanExp_)
    {
        // Constructor
        setBooleanExp(_booleanExp_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanExpExp(
            cloneNode(this._booleanExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanExpExp(this);
    }

    public PBooleanExp getBooleanExp()
    {
        return this._booleanExp_;
    }

    public void setBooleanExp(PBooleanExp node)
    {
        if(this._booleanExp_ != null)
        {
            this._booleanExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanExp_ == child)
        {
            this._booleanExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanExp_ == oldChild)
        {
            setBooleanExp((PBooleanExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
