/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanBooleanExp extends PBooleanExp
{
    private TBooleanConstant _booleanConstant_;

    public ABooleanBooleanExp()
    {
        // Constructor
    }

    public ABooleanBooleanExp(
        @SuppressWarnings("hiding") TBooleanConstant _booleanConstant_)
    {
        // Constructor
        setBooleanConstant(_booleanConstant_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanBooleanExp(
            cloneNode(this._booleanConstant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanBooleanExp(this);
    }

    public TBooleanConstant getBooleanConstant()
    {
        return this._booleanConstant_;
    }

    public void setBooleanConstant(TBooleanConstant node)
    {
        if(this._booleanConstant_ != null)
        {
            this._booleanConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanConstant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanConstant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanConstant_ == child)
        {
            this._booleanConstant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanConstant_ == oldChild)
        {
            setBooleanConstant((TBooleanConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
