/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ACadeiaTipoBase extends PTipoBase
{
    private TStringKw _stringKw_;

    public ACadeiaTipoBase()
    {
        // Constructor
    }

    public ACadeiaTipoBase(
        @SuppressWarnings("hiding") TStringKw _stringKw_)
    {
        // Constructor
        setStringKw(_stringKw_);

    }

    @Override
    public Object clone()
    {
        return new ACadeiaTipoBase(
            cloneNode(this._stringKw_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACadeiaTipoBase(this);
    }

    public TStringKw getStringKw()
    {
        return this._stringKw_;
    }

    public void setStringKw(TStringKw node)
    {
        if(this._stringKw_ != null)
        {
            this._stringKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringKw_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringKw_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringKw_ == child)
        {
            this._stringKw_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringKw_ == oldChild)
        {
            setStringKw((TStringKw) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
