/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ACadeiaTipo extends PTipo
{
    private TCadeia _cadeia_;

    public ACadeiaTipo()
    {
        // Constructor
    }

    public ACadeiaTipo(
        @SuppressWarnings("hiding") TCadeia _cadeia_)
    {
        // Constructor
        setCadeia(_cadeia_);

    }

    @Override
    public Object clone()
    {
        return new ACadeiaTipo(
            cloneNode(this._cadeia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACadeiaTipo(this);
    }

    public TCadeia getCadeia()
    {
        return this._cadeia_;
    }

    public void setCadeia(TCadeia node)
    {
        if(this._cadeia_ != null)
        {
            this._cadeia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cadeia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cadeia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cadeia_ == child)
        {
            this._cadeia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cadeia_ == oldChild)
        {
            setCadeia((TCadeia) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
