/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ACadeiaExp extends PExp
{
    private TCadeiaConstant _cadeiaConstant_;

    public ACadeiaExp()
    {
        // Constructor
    }

    public ACadeiaExp(
        @SuppressWarnings("hiding") TCadeiaConstant _cadeiaConstant_)
    {
        // Constructor
        setCadeiaConstant(_cadeiaConstant_);

    }

    @Override
    public Object clone()
    {
        return new ACadeiaExp(
            cloneNode(this._cadeiaConstant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACadeiaExp(this);
    }

    public TCadeiaConstant getCadeiaConstant()
    {
        return this._cadeiaConstant_;
    }

    public void setCadeiaConstant(TCadeiaConstant node)
    {
        if(this._cadeiaConstant_ != null)
        {
            this._cadeiaConstant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cadeiaConstant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cadeiaConstant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cadeiaConstant_ == child)
        {
            this._cadeiaConstant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cadeiaConstant_ == oldChild)
        {
            setCadeiaConstant((TCadeiaConstant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
