/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ACFuncExpAux extends PExpAux
{
    private PChamadaFuncao _chamadaFuncao_;

    public ACFuncExpAux()
    {
        // Constructor
    }

    public ACFuncExpAux(
        @SuppressWarnings("hiding") PChamadaFuncao _chamadaFuncao_)
    {
        // Constructor
        setChamadaFuncao(_chamadaFuncao_);

    }

    @Override
    public Object clone()
    {
        return new ACFuncExpAux(
            cloneNode(this._chamadaFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACFuncExpAux(this);
    }

    public PChamadaFuncao getChamadaFuncao()
    {
        return this._chamadaFuncao_;
    }

    public void setChamadaFuncao(PChamadaFuncao node)
    {
        if(this._chamadaFuncao_ != null)
        {
            this._chamadaFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamadaFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamadaFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamadaFuncao_ == child)
        {
            this._chamadaFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamadaFuncao_ == oldChild)
        {
            setChamadaFuncao((PChamadaFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
