/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AConjDisjuncao extends PDisjuncao
{
    private PConjuncao _conjuncao_;

    public AConjDisjuncao()
    {
        // Constructor
    }

    public AConjDisjuncao(
        @SuppressWarnings("hiding") PConjuncao _conjuncao_)
    {
        // Constructor
        setConjuncao(_conjuncao_);

    }

    @Override
    public Object clone()
    {
        return new AConjDisjuncao(
            cloneNode(this._conjuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConjDisjuncao(this);
    }

    public PConjuncao getConjuncao()
    {
        return this._conjuncao_;
    }

    public void setConjuncao(PConjuncao node)
    {
        if(this._conjuncao_ != null)
        {
            this._conjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conjuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conjuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conjuncao_ == child)
        {
            this._conjuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conjuncao_ == oldChild)
        {
            setConjuncao((PConjuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
