/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AConditionalExp extends PExp
{
    private PConditional _conditional_;

    public AConditionalExp()
    {
        // Constructor
    }

    public AConditionalExp(
        @SuppressWarnings("hiding") PConditional _conditional_)
    {
        // Constructor
        setConditional(_conditional_);

    }

    @Override
    public Object clone()
    {
        return new AConditionalExp(
            cloneNode(this._conditional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionalExp(this);
    }

    public PConditional getConditional()
    {
        return this._conditional_;
    }

    public void setConditional(PConditional node)
    {
        if(this._conditional_ != null)
        {
            this._conditional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditional_ == child)
        {
            this._conditional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditional_ == oldChild)
        {
            setConditional((PConditional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
