/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AConstSubBloco extends PSubBloco
{
    private PDecConst _decConst_;

    public AConstSubBloco()
    {
        // Constructor
    }

    public AConstSubBloco(
        @SuppressWarnings("hiding") PDecConst _decConst_)
    {
        // Constructor
        setDecConst(_decConst_);

    }

    @Override
    public Object clone()
    {
        return new AConstSubBloco(
            cloneNode(this._decConst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstSubBloco(this);
    }

    public PDecConst getDecConst()
    {
        return this._decConst_;
    }

    public void setDecConst(PDecConst node)
    {
        if(this._decConst_ != null)
        {
            this._decConst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decConst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decConst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decConst_ == child)
        {
            this._decConst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decConst_ == oldChild)
        {
            setDecConst((PDecConst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
