/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncDecProcOrDecFunc extends PDecProcOrDecFunc
{
    private PDecFunc _decFunc_;

    public ADecFuncDecProcOrDecFunc()
    {
        // Constructor
    }

    public ADecFuncDecProcOrDecFunc(
        @SuppressWarnings("hiding") PDecFunc _decFunc_)
    {
        // Constructor
        setDecFunc(_decFunc_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncDecProcOrDecFunc(
            cloneNode(this._decFunc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncDecProcOrDecFunc(this);
    }

    public PDecFunc getDecFunc()
    {
        return this._decFunc_;
    }

    public void setDecFunc(PDecFunc node)
    {
        if(this._decFunc_ != null)
        {
            this._decFunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decFunc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decFunc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decFunc_ == child)
        {
            this._decFunc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decFunc_ == oldChild)
        {
            setDecFunc((PDecFunc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
