/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ADividitiveMultiplicativeExp extends PMultiplicativeExp
{
    private PMultiplicativeExp _multiplicativeExp_;
    private TDiv _div_;
    private PNumber _number_;

    public ADividitiveMultiplicativeExp()
    {
        // Constructor
    }

    public ADividitiveMultiplicativeExp(
        @SuppressWarnings("hiding") PMultiplicativeExp _multiplicativeExp_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PNumber _number_)
    {
        // Constructor
        setMultiplicativeExp(_multiplicativeExp_);

        setDiv(_div_);

        setNumber(_number_);

    }

    @Override
    public Object clone()
    {
        return new ADividitiveMultiplicativeExp(
            cloneNode(this._multiplicativeExp_),
            cloneNode(this._div_),
            cloneNode(this._number_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADividitiveMultiplicativeExp(this);
    }

    public PMultiplicativeExp getMultiplicativeExp()
    {
        return this._multiplicativeExp_;
    }

    public void setMultiplicativeExp(PMultiplicativeExp node)
    {
        if(this._multiplicativeExp_ != null)
        {
            this._multiplicativeExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplicativeExp_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(PNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiplicativeExp_)
            + toString(this._div_)
            + toString(this._number_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiplicativeExp_ == child)
        {
            this._multiplicativeExp_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multiplicativeExp_ == oldChild)
        {
            setMultiplicativeExp((PMultiplicativeExp) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((PNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
