/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AEqualExpRelationalExp extends PRelationalExp
{
    private PRelationalExp _relationalExp_;
    private TEqual _equal_;
    private PAdditiveExp _additiveExp_;

    public AEqualExpRelationalExp()
    {
        // Constructor
    }

    public AEqualExpRelationalExp(
        @SuppressWarnings("hiding") PRelationalExp _relationalExp_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") PAdditiveExp _additiveExp_)
    {
        // Constructor
        setRelationalExp(_relationalExp_);

        setEqual(_equal_);

        setAdditiveExp(_additiveExp_);

    }

    @Override
    public Object clone()
    {
        return new AEqualExpRelationalExp(
            cloneNode(this._relationalExp_),
            cloneNode(this._equal_),
            cloneNode(this._additiveExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualExpRelationalExp(this);
    }

    public PRelationalExp getRelationalExp()
    {
        return this._relationalExp_;
    }

    public void setRelationalExp(PRelationalExp node)
    {
        if(this._relationalExp_ != null)
        {
            this._relationalExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalExp_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public PAdditiveExp getAdditiveExp()
    {
        return this._additiveExp_;
    }

    public void setAdditiveExp(PAdditiveExp node)
    {
        if(this._additiveExp_ != null)
        {
            this._additiveExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._additiveExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relationalExp_)
            + toString(this._equal_)
            + toString(this._additiveExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relationalExp_ == child)
        {
            this._relationalExp_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._additiveExp_ == child)
        {
            this._additiveExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relationalExp_ == oldChild)
        {
            setRelationalExp((PRelationalExp) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._additiveExp_ == oldChild)
        {
            setAdditiveExp((PAdditiveExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
