/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AFloatTypeSpecifier extends PTypeSpecifier
{
    private PFloatSpecifier _floatSpecifier_;

    public AFloatTypeSpecifier()
    {
        // Constructor
    }

    public AFloatTypeSpecifier(
        @SuppressWarnings("hiding") PFloatSpecifier _floatSpecifier_)
    {
        // Constructor
        setFloatSpecifier(_floatSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new AFloatTypeSpecifier(
            cloneNode(this._floatSpecifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatTypeSpecifier(this);
    }

    public PFloatSpecifier getFloatSpecifier()
    {
        return this._floatSpecifier_;
    }

    public void setFloatSpecifier(PFloatSpecifier node)
    {
        if(this._floatSpecifier_ != null)
        {
            this._floatSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._floatSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._floatSpecifier_ == child)
        {
            this._floatSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._floatSpecifier_ == oldChild)
        {
            setFloatSpecifier((PFloatSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
