/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterRelacao extends PRelacao
{
    private PRelacao _relacao_;
    private TGreater _greater_;
    private PAdicao _adicao_;

    public AGreaterRelacao()
    {
        // Constructor
    }

    public AGreaterRelacao(
        @SuppressWarnings("hiding") PRelacao _relacao_,
        @SuppressWarnings("hiding") TGreater _greater_,
        @SuppressWarnings("hiding") PAdicao _adicao_)
    {
        // Constructor
        setRelacao(_relacao_);

        setGreater(_greater_);

        setAdicao(_adicao_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterRelacao(
            cloneNode(this._relacao_),
            cloneNode(this._greater_),
            cloneNode(this._adicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterRelacao(this);
    }

    public PRelacao getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(PRelacao node)
    {
        if(this._relacao_ != null)
        {
            this._relacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacao_ = node;
    }

    public TGreater getGreater()
    {
        return this._greater_;
    }

    public void setGreater(TGreater node)
    {
        if(this._greater_ != null)
        {
            this._greater_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greater_ = node;
    }

    public PAdicao getAdicao()
    {
        return this._adicao_;
    }

    public void setAdicao(PAdicao node)
    {
        if(this._adicao_ != null)
        {
            this._adicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacao_)
            + toString(this._greater_)
            + toString(this._adicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacao_ == child)
        {
            this._relacao_ = null;
            return;
        }

        if(this._greater_ == child)
        {
            this._greater_ = null;
            return;
        }

        if(this._adicao_ == child)
        {
            this._adicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relacao_ == oldChild)
        {
            setRelacao((PRelacao) newChild);
            return;
        }

        if(this._greater_ == oldChild)
        {
            setGreater((TGreater) newChild);
            return;
        }

        if(this._adicao_ == oldChild)
        {
            setAdicao((PAdicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
