/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AIntTipoKw extends PTipoKw
{
    private TIntKw _intKw_;

    public AIntTipoKw()
    {
        // Constructor
    }

    public AIntTipoKw(
        @SuppressWarnings("hiding") TIntKw _intKw_)
    {
        // Constructor
        setIntKw(_intKw_);

    }

    @Override
    public Object clone()
    {
        return new AIntTipoKw(
            cloneNode(this._intKw_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntTipoKw(this);
    }

    public TIntKw getIntKw()
    {
        return this._intKw_;
    }

    public void setIntKw(TIntKw node)
    {
        if(this._intKw_ != null)
        {
            this._intKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intKw_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intKw_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intKw_ == child)
        {
            this._intKw_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intKw_ == oldChild)
        {
            setIntKw((TIntKw) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
