/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosParametros extends PParametros
{
    private PParametrosAux _parametrosAux_;

    public AParametrosParametros()
    {
        // Constructor
    }

    public AParametrosParametros(
        @SuppressWarnings("hiding") PParametrosAux _parametrosAux_)
    {
        // Constructor
        setParametrosAux(_parametrosAux_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosParametros(
            cloneNode(this._parametrosAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosParametros(this);
    }

    public PParametrosAux getParametrosAux()
    {
        return this._parametrosAux_;
    }

    public void setParametrosAux(PParametrosAux node)
    {
        if(this._parametrosAux_ != null)
        {
            this._parametrosAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametrosAux_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametrosAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametrosAux_ == child)
        {
            this._parametrosAux_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametrosAux_ == oldChild)
        {
            setParametrosAux((PParametrosAux) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
