/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class APipeParametroClosureParametrosAux extends PParametrosAux
{
    private PParametro _parametro_;
    private final LinkedList<PPipeParametro> _pipeParametro_ = new LinkedList<PPipeParametro>();

    public APipeParametroClosureParametrosAux()
    {
        // Constructor
    }

    public APipeParametroClosureParametrosAux(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _pipeParametro_)
    {
        // Constructor
        setParametro(_parametro_);

        setPipeParametro(_pipeParametro_);

    }

    @Override
    public Object clone()
    {
        return new APipeParametroClosureParametrosAux(
            cloneNode(this._parametro_),
            cloneList(this._pipeParametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPipeParametroClosureParametrosAux(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PPipeParametro> getPipeParametro()
    {
        return this._pipeParametro_;
    }

    public void setPipeParametro(List<?> list)
    {
        for(PPipeParametro e : this._pipeParametro_)
        {
            e.parent(null);
        }
        this._pipeParametro_.clear();

        for(Object obj_e : list)
        {
            PPipeParametro e = (PPipeParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._pipeParametro_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._pipeParametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._pipeParametro_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PPipeParametro> i = this._pipeParametro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPipeParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
