/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import java.util.*;
import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private final LinkedList<PDecVarOrConst> _decVarOrConst_ = new LinkedList<PDecVarOrConst>();
    private final LinkedList<PDecProcOrFunc> _decProcOrFunc_ = new LinkedList<PDecProcOrFunc>();

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") List<?> _decVarOrConst_,
        @SuppressWarnings("hiding") List<?> _decProcOrFunc_)
    {
        // Constructor
        setDecVarOrConst(_decVarOrConst_);

        setDecProcOrFunc(_decProcOrFunc_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneList(this._decVarOrConst_),
            cloneList(this._decProcOrFunc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public LinkedList<PDecVarOrConst> getDecVarOrConst()
    {
        return this._decVarOrConst_;
    }

    public void setDecVarOrConst(List<?> list)
    {
        for(PDecVarOrConst e : this._decVarOrConst_)
        {
            e.parent(null);
        }
        this._decVarOrConst_.clear();

        for(Object obj_e : list)
        {
            PDecVarOrConst e = (PDecVarOrConst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decVarOrConst_.add(e);
        }
    }

    public LinkedList<PDecProcOrFunc> getDecProcOrFunc()
    {
        return this._decProcOrFunc_;
    }

    public void setDecProcOrFunc(List<?> list)
    {
        for(PDecProcOrFunc e : this._decProcOrFunc_)
        {
            e.parent(null);
        }
        this._decProcOrFunc_.clear();

        for(Object obj_e : list)
        {
            PDecProcOrFunc e = (PDecProcOrFunc) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decProcOrFunc_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVarOrConst_)
            + toString(this._decProcOrFunc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVarOrConst_.remove(child))
        {
            return;
        }

        if(this._decProcOrFunc_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecVarOrConst> i = this._decVarOrConst_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecVarOrConst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PDecProcOrFunc> i = this._decProcOrFunc_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecProcOrFunc) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
