/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class AProcComando extends PComando
{
    private PChamadaProcedimento _chamadaProcedimento_;
    private TSemi _semi_;

    public AProcComando()
    {
        // Constructor
    }

    public AProcComando(
        @SuppressWarnings("hiding") PChamadaProcedimento _chamadaProcedimento_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setChamadaProcedimento(_chamadaProcedimento_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AProcComando(
            cloneNode(this._chamadaProcedimento_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcComando(this);
    }

    public PChamadaProcedimento getChamadaProcedimento()
    {
        return this._chamadaProcedimento_;
    }

    public void setChamadaProcedimento(PChamadaProcedimento node)
    {
        if(this._chamadaProcedimento_ != null)
        {
            this._chamadaProcedimento_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamadaProcedimento_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamadaProcedimento_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamadaProcedimento_ == child)
        {
            this._chamadaProcedimento_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamadaProcedimento_ == oldChild)
        {
            setChamadaProcedimento((PChamadaProcedimento) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
