/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ARelationalExp extends PExp
{
    private PRelationalExp _relationalExp_;

    public ARelationalExp()
    {
        // Constructor
    }

    public ARelationalExp(
        @SuppressWarnings("hiding") PRelationalExp _relationalExp_)
    {
        // Constructor
        setRelationalExp(_relationalExp_);

    }

    @Override
    public Object clone()
    {
        return new ARelationalExp(
            cloneNode(this._relationalExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelationalExp(this);
    }

    public PRelationalExp getRelationalExp()
    {
        return this._relationalExp_;
    }

    public void setRelationalExp(PRelationalExp node)
    {
        if(this._relationalExp_ != null)
        {
            this._relationalExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relationalExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relationalExp_ == child)
        {
            this._relationalExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relationalExp_ == oldChild)
        {
            setRelationalExp((PRelationalExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
