/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ARelUnariaProduto extends PProduto
{
    private PRelUnaria _relUnaria_;

    public ARelUnariaProduto()
    {
        // Constructor
    }

    public ARelUnariaProduto(
        @SuppressWarnings("hiding") PRelUnaria _relUnaria_)
    {
        // Constructor
        setRelUnaria(_relUnaria_);

    }

    @Override
    public Object clone()
    {
        return new ARelUnariaProduto(
            cloneNode(this._relUnaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelUnariaProduto(this);
    }

    public PRelUnaria getRelUnaria()
    {
        return this._relUnaria_;
    }

    public void setRelUnaria(PRelUnaria node)
    {
        if(this._relUnaria_ != null)
        {
            this._relUnaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relUnaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relUnaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relUnaria_ == child)
        {
            this._relUnaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relUnaria_ == oldChild)
        {
            setRelUnaria((PRelUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
