/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class ASubtractiveExpExp extends PExp
{
    private PSubtractiveExp _subtractiveExp_;

    public ASubtractiveExpExp()
    {
        // Constructor
    }

    public ASubtractiveExpExp(
        @SuppressWarnings("hiding") PSubtractiveExp _subtractiveExp_)
    {
        // Constructor
        setSubtractiveExp(_subtractiveExp_);

    }

    @Override
    public Object clone()
    {
        return new ASubtractiveExpExp(
            cloneNode(this._subtractiveExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtractiveExpExp(this);
    }

    public PSubtractiveExp getSubtractiveExp()
    {
        return this._subtractiveExp_;
    }

    public void setSubtractiveExp(PSubtractiveExp node)
    {
        if(this._subtractiveExp_ != null)
        {
            this._subtractiveExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subtractiveExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subtractiveExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subtractiveExp_ == child)
        {
            this._subtractiveExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subtractiveExp_ == oldChild)
        {
            setSubtractiveExp((PSubtractiveExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
