/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TImprima extends Token
{
    public TImprima()
    {
        super.setText("imprima");
    }

    public TImprima(int line, int pos)
    {
        super.setText("imprima");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TImprima(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImprima(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TImprima text.");
    }
}
