/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TPrincipal extends Token
{
    public TPrincipal()
    {
        super.setText("principal");
    }

    public TPrincipal(int line, int pos)
    {
        super.setText("principal");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrincipal(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrincipal(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrincipal text.");
    }
}
