/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TProcedureKeyword extends Token
{
    public TProcedureKeyword()
    {
        super.setText("procedimento");
    }

    public TProcedureKeyword(int line, int pos)
    {
        super.setText("procedimento");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProcedureKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProcedureKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProcedureKeyword text.");
    }
}
