/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TTCadeia extends Token
{
    public TTCadeia()
    {
        super.setText("cadeia");
    }

    public TTCadeia(int line, int pos)
    {
        super.setText("cadeia");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTCadeia(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTCadeia(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTCadeia text.");
    }
}
