/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.node;

import sarapatel.analysis.*;

@SuppressWarnings("nls")
public final class TTermine extends Token
{
    public TTermine()
    {
        super.setText("termine");
    }

    public TTermine(int line, int pos)
    {
        super.setText("termine");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTermine(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTermine(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTermine text.");
    }
}
