/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.analysis;

import java.util.*;
import sarapatel.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcDecProcOrFunc(AProcDecProcOrFunc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncDecProcOrFunc(AFuncDecProcOrFunc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarDecVarOrConst(AVarDecVarOrConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstDecVarOrConst(AConstDecVarOrConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecConst(ADecConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdIdDec(AIdIdDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdAtrIdDec(AIdAtrIdDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecProc(ADecProc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecFunc(ADecFunc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaFuncao(AChamadaFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaProcedimento(AChamadaProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseTipo(ABaseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrTipo(AArrTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseTipoFunc(ABaseTipoFunc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrTipoFunc(AArrTipoFunc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntTipoKw(AIntTipoKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolTipoKw(ABoolTipoKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealTipoKw(ARealTipoKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACadeiaTipoKw(ACadeiaTipoKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAttr(AAttr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdArrAttr(AIdArrAttr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrArrAttr(AArrArrAttr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrayComp(AArrayComp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParam(AParam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPipeParam(APipeParam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParTipoParam(AParTipoParam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrParTipoParam(AArrParTipoParam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeComando(ASeComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeSenaoComando(ASeSenaoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoComando(AEnquantoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAttrComando(AAttrComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcComando(AProcComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeComandoAux(ASeComandoAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoComandoAux(AEnquantoComandoAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcComandoAux(AProcComandoAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAttrComandoAux(AAttrComandoAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComandoAux(ABlocoComandoAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarSubBloco(AVarSubBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstSubBloco(AConstSubBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdValor(AIdValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpValor(AExpValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeExp(ASeExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpList(AExpList node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPipeExpPipeExp(APipeExpPipeExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoExpressoes(ABlocoExpressoes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADisjCondicao(ADisjCondicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeExpCondicao(ASeExpCondicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConjDisjuncao(AConjDisjuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuDisjuncao(AOuDisjuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelConjuncao(ARelConjuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEConjuncao(AEConjuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAdicaoRelacao(AAdicaoRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEqualRelacao(AEqualRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGreaterEqRelacao(AGreaterEqRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGreaterRelacao(AGreaterRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProdutoAdicao(AProdutoAdicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaAdicao(ASomaAdicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMinusAdicao(AMinusAdicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelUnariaProduto(ARelUnariaProduto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultProduto(AMultProduto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivProduto(ADivProduto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModProduto(AModProduto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAuxRelUnaria(AAuxRelUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaisRelUnaria(AMaisRelUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosRelUnaria(AMenosRelUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegaRelUnaria(ANegaRelUnaria node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntExpAux(AIntExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolExpAux(ABoolExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealExpAux(ARealExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACadeiaExpAux(ACadeiaExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAValorExpAux(AValorExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParExpAux(AParExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACFuncExpAux(ACFuncExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAArrayCExpAux(AArrayCExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABExpExpAux(ABExpExpAux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVar(TVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTConst(TConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEnquanto(TEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFuncao(TFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProcedimento(TProcedimento node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTE(TE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNegacao(TNegacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComece(TComece node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTermine(TTermine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIntKw(TIntKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFloatKw(TFloatKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStringKw(TStringKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBoolKw(TBoolKw node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInt(TInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFloat(TFloat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBool(TBool node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStar(TStar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGreater(TGreater node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGreaterEq(TGreaterEq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEqual(TEqual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBrkt(TLBrkt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBrkt(TRBrkt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDd(TDd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMainInit(TMainInit node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSemi(TSemi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPipe(TPipe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColon(TColon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMlComment(TMlComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
