/* This file was generated by SableCC (http://www.sablecc.org/). */

package sarapatel.lexer;

import java.io.*;
import sarapatel.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDigit(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLetter(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBracket(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBracket(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPipe(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAttr(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreater(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreaterOrEqual(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqual(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComece(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTermine(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImprima(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSize(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTInteiro(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTReal(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTCadeia(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTBooleano(line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatingConstant(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntegerConstant(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCadeiaConstant(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleanConstant(text, line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEol(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {37, 37, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 48, 15}, {49, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {95, 95, 22}, {97, 97, 22}, {98, 98, 25}, {99, 99, 26}, {100, 100, 22}, {101, 101, 27}, {102, 102, 28}, {103, 104, 22}, {105, 105, 29}, {106, 107, 22}, {108, 108, 30}, {109, 109, 22}, {110, 110, 31}, {111, 111, 32}, {112, 112, 33}, {113, 113, 22}, {114, 114, 34}, {115, 115, 35}, {116, 116, 36}, {117, 117, 22}, {118, 118, 37}, {119, 122, 22}, {123, 123, 38}, {124, 124, 39}, {125, 125, 40}, },
            {{9, 9, 1}, {10, 10, 41}, {13, 13, 42}, {32, 32, 4}, },
            {{9, 32, -3}, },
            {{9, 9, 1}, {10, 10, 43}, {13, 32, -3}, },
            {{9, 32, -3}, },
            {},
            {{0, 9, 44}, {11, 12, 44}, {14, 38, 44}, {40, 65535, 44}, },
            {},
            {},
            {},
            {},
            {},
            {{45, 45, 45}, },
            {},
            {},
            {{98, 98, 46}, },
            {{48, 57, 47}, },
            {},
            {},
            {{60, 60, 48}, },
            {},
            {{61, 61, 49}, },
            {{48, 57, 50}, {65, 90, 51}, {95, 95, 51}, {97, 122, 51}, },
            {},
            {},
            {{48, 95, -24}, {97, 110, 51}, {111, 111, 52}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 97, 53}, {98, 110, 51}, {111, 111, 54}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 109, 51}, {110, 110, 55}, {111, 122, 51}, },
            {{48, 95, -24}, {97, 97, 56}, {98, 116, 51}, {117, 117, 57}, {118, 122, 51}, },
            {{48, 95, -24}, {97, 108, 51}, {109, 109, 58}, {110, 110, 59}, {111, 122, 51}, },
            {{48, 95, -24}, {97, 100, 51}, {101, 101, 60}, {102, 122, 51}, },
            {{48, 95, -24}, {97, 97, 61}, {98, 122, 51}, },
            {{48, 95, -24}, {97, 116, 51}, {117, 117, 62}, {118, 122, 51}, },
            {{48, 95, -24}, {97, 113, 51}, {114, 114, 63}, {115, 122, 51}, },
            {{48, 100, -32}, {101, 101, 64}, {102, 122, 51}, },
            {{48, 100, -32}, {101, 101, 65}, {102, 104, 51}, {105, 105, 66}, {106, 122, 51}, },
            {{48, 100, -32}, {101, 101, 67}, {102, 122, 51}, },
            {{48, 95, -24}, {97, 97, 68}, {98, 100, 51}, {101, 101, 69}, {102, 122, 51}, },
            {{0, 44, 70}, {45, 45, 71}, {46, 124, 70}, {125, 125, 72}, {126, 65535, 70}, },
            {},
            {},
            {{9, 32, -3}, },
            {{9, 9, 1}, {10, 10, 73}, {13, 32, -3}, },
            {{9, 32, -3}, },
            {{0, 38, -8}, {39, 39, 74}, {40, 65535, 44}, },
            {{0, 9, 75}, {10, 10, 76}, {11, 12, 75}, {13, 13, 77}, {14, 65535, 75}, },
            {{48, 48, 78}, {49, 49, 79}, },
            {{44, 44, 80}, {48, 57, 47}, },
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 110, -27}, {111, 111, 81}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 99, 51}, {100, 100, 82}, {101, 122, 51}, },
            {{48, 108, -31}, {109, 109, 83}, {110, 110, 84}, {111, 122, 51}, },
            {{48, 95, -24}, {97, 112, 51}, {113, 113, 85}, {114, 122, 51}, },
            {{48, 95, -24}, {97, 107, 51}, {108, 108, 86}, {109, 122, 51}, },
            {{48, 109, -29}, {110, 110, 87}, {111, 122, 51}, },
            {{48, 95, -24}, {97, 111, 51}, {112, 112, 88}, {113, 122, 51}, },
            {{48, 95, -24}, {97, 115, 51}, {116, 116, 89}, {117, 122, 51}, },
            {{48, 95, -24}, {97, 104, 51}, {105, 105, 90}, {106, 122, 51}, },
            {{48, 110, -27}, {111, 111, 91}, {112, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 110, -27}, {111, 111, 92}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 97, 93}, {98, 122, 51}, },
            {{48, 109, -29}, {110, 110, 94}, {111, 122, 51}, },
            {{48, 95, -24}, {97, 121, 51}, {122, 122, 95}, },
            {{48, 113, -35}, {114, 114, 96}, {115, 122, 51}, },
            {{48, 113, -35}, {114, 114, 97}, {115, 122, 51}, },
            {{48, 113, -35}, {114, 114, 98}, {115, 122, 51}, },
            {{0, 65535, -40}, },
            {{0, 44, 70}, {45, 45, 99}, {46, 65535, -40}, },
            {{10, 10, 100}, {13, 13, 101}, },
            {{9, 32, -3}, },
            {},
            {{0, 65535, -47}, },
            {},
            {{10, 10, 102}, },
            {{48, 49, -48}, },
            {{48, 49, -48}, },
            {{48, 57, 103}, },
            {{48, 107, -58}, {108, 108, 104}, {109, 122, 51}, },
            {{48, 100, -32}, {101, 101, 105}, {102, 122, 51}, },
            {{48, 100, -32}, {101, 101, 106}, {102, 122, 51}, },
            {{48, 95, -24}, {97, 114, 51}, {115, 115, 107}, {116, 122, 51}, },
            {{48, 116, -34}, {117, 117, 108}, {118, 122, 51}, },
            {{48, 114, -86}, {115, 115, 109}, {116, 122, 51}, },
            {{48, 95, -24}, {97, 98, 51}, {99, 99, 110}, {100, 122, 51}, },
            {{48, 113, -35}, {114, 114, 111}, {115, 122, 51}, },
            {{48, 100, -32}, {101, 101, 112}, {102, 122, 51}, },
            {{48, 95, -24}, {97, 97, 113}, {98, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 98, -89}, {99, 99, 114}, {100, 122, 51}, },
            {{48, 107, -58}, {108, 108, 115}, {109, 122, 51}, },
            {{48, 95, -24}, {97, 97, 116}, {98, 122, 51}, },
            {{48, 100, -32}, {101, 101, 117}, {102, 122, 51}, },
            {{48, 108, -31}, {109, 109, 118}, {110, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 99, -55}, {100, 100, 119}, {101, 122, 51}, },
            {{0, 9, 120}, {10, 10, 121}, {11, 12, 120}, {13, 13, 122}, {14, 44, 120}, {45, 45, 123}, {46, 124, 120}, {125, 125, 124}, {126, 65535, 120}, },
            {},
            {{10, 10, 125}, },
            {},
            {{48, 57, 103}, },
            {{48, 100, -32}, {101, 101, 126}, {102, 122, 51}, },
            {{48, 104, -62}, {105, 105, 127}, {106, 122, 51}, },
            {{48, 98, -89}, {99, 99, 128}, {100, 122, 51}, },
            {{48, 115, -61}, {116, 116, 129}, {117, 122, 51}, },
            {{48, 95, -24}, {97, 97, 130}, {98, 122, 51}, },
            {{48, 110, -27}, {111, 111, 131}, {112, 122, 51}, },
            {{48, 95, -24}, {97, 97, 132}, {98, 122, 51}, },
            {{48, 104, -62}, {105, 105, 133}, {106, 122, 51}, },
            {{48, 104, -62}, {105, 105, 134}, {106, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 100, -32}, {101, 101, 135}, {102, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 110, -27}, {111, 111, 136}, {112, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 104, -62}, {105, 105, 137}, {106, 122, 51}, },
            {{48, 95, -24}, {97, 97, 138}, {98, 122, 51}, },
            {{0, 44, -101}, {45, 45, 139}, {46, 65535, -101}, },
            {{0, 65535, -40}, },
            {{0, 9, 70}, {10, 10, 140}, {11, 44, 70}, {45, 65535, -40}, },
            {{0, 65535, -101}, },
            {{0, 9, 120}, {10, 10, 141}, {11, 12, 120}, {13, 13, 142}, {14, 65535, -122}, },
            {},
            {{48, 95, -24}, {97, 97, 143}, {98, 122, 51}, },
            {{48, 95, -24}, {97, 97, 144}, {98, 122, 51}, },
            {{48, 100, -32}, {101, 101, 145}, {102, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 109, -29}, {110, 110, 146}, {111, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 110, -27}, {111, 111, 147}, {112, 122, 51}, },
            {{48, 108, -31}, {109, 109, 148}, {110, 122, 51}, },
            {{48, 113, -35}, {114, 114, 149}, {115, 122, 51}, },
            {{48, 99, -55}, {100, 100, 150}, {101, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 109, -29}, {110, 110, 151}, {111, 122, 51}, },
            {{48, 99, -55}, {100, 100, 152}, {101, 122, 51}, },
            {{0, 65535, -101}, },
            {{0, 65535, -40}, },
            {{0, 65535, -40}, },
            {{0, 9, 70}, {10, 10, 153}, {11, 65535, -124}, },
            {{48, 109, -29}, {110, 110, 154}, {111, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 115, -61}, {116, 116, 155}, {117, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 156}, {98, 122, 51}, },
            {{48, 110, -27}, {111, 111, 157}, {112, 122, 51}, },
            {{48, 104, -62}, {105, 105, 158}, {106, 122, 51}, },
            {{48, 100, -32}, {101, 101, 159}, {102, 122, 51}, },
            {{48, 100, -32}, {101, 101, 160}, {102, 122, 51}, },
            {{0, 65535, -40}, },
            {{48, 110, -27}, {111, 111, 161}, {112, 122, 51}, },
            {{48, 110, -27}, {111, 111, 162}, {112, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 108, -31}, {109, 109, 163}, {110, 122, 51}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 100, -32}, {101, 101, 164}, {102, 122, 51}, },
            {{48, 109, -29}, {110, 110, 165}, {111, 122, 51}, },
            {{48, 115, -61}, {116, 116, 166}, {117, 122, 51}, },
            {{48, 110, -27}, {111, 111, 167}, {112, 122, 51}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 46, 45, 45, 46, 14, -1, 6, 7, 12, 15, 3, 16, 2, 13, 0, 0, 4, 5, -1, 24, 22, 1, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 17, 11, 46, 46, 45, -1, 48, -1, 42, 18, 23, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 20, 47, 47, 25, 47, 47, 47, 47, -1, -1, 48, 46, 43, 48, 48, 48, 42, 42, -1, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 21, 47, 47, 47, 47, 47, 32, 47, -1, 48, 48, 48, 41, 47, 47, 47, 47, 47, 47, 47, 47, 47, 35, 47, 38, 47, 36, 47, 47, -1, -1, -1, -1, 48, 48, 47, 47, 47, 33, 47, 44, 47, 47, 47, 47, 26, 47, 47, -1, -1, 48, 48, 47, 39, 30, 47, 27, 47, 47, 47, 47, 47, 48, 47, 47, 34, 37, 47, 31, 44, 40, 29, 47, 47, 47, 47, 28, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
